package com.zalando.onboarding.validation;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * Every vector here is published in python-stdnum's pl/regon.py doctest, an external
 * reference implementation, rather than generated by this codebase.
 *
 * @see <a href="https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/pl/regon.py">stdnum/pl/regon.py</a>
 */
class RegonValidatorTest {

    private final RegonValidator validator = new RegonValidator();

    @ParameterizedTest
    @ValueSource(strings = {
            "192598184",       // published valid, 9-digit
            "123456785",       // published valid, 9-digit
            "12345678512347",  // published valid, 14-digit
    })
    void acceptsPublishedValidRegons(String regon) {
        assertThat(validator.validate("regon", regon)).isEmpty();
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "192598183",       // published invalid: 9-digit check digit wrong
            "12345678512348",  // published invalid: final check digit wrong
    })
    void rejectsPublishedInvalidRegons(String regon) {
        assertThat(validator.validate("regon", regon))
                .get()
                .extracting(Violation::code)
                .isEqualTo(ViolationCode.CHECKSUM_INVALID);
    }

    /**
     * The vector that justifies checking both check digits. 12345678612342 satisfies the
     * 14-digit checksum and is rejected by the reference implementation only because the
     * 9-digit entity number embedded in its first nine digits does not check out. An
     * implementation that verified the final digit alone would accept it.
     */
    @Test
    void rejectsAFourteenDigitRegonWhoseEmbeddedNineDigitNumberIsWrong() {
        String published = "12345678612342";

        assertThat(new RegonValidator().validate("regon", published))
                .as("caught only by the embedded 9-digit check")
                .get()
                .extracting(Violation::code)
                .isEqualTo(ViolationCode.CHECKSUM_INVALID);

        // Guard the premise: the final 14-digit check digit really does pass here, so this
        // test would silently stop testing anything if the vector were changed.
        int[] weights14 = {2, 4, 8, 5, 0, 9, 7, 3, 6, 1, 2, 4, 8};
        int sum = 0;
        for (int i = 0; i < weights14.length; i++) {
            sum += weights14[i] * Character.getNumericValue(published.charAt(i));
        }
        assertThat(sum % 11 % 10)
                .as("the 14-digit checksum alone accepts this number")
                .isEqualTo(Character.getNumericValue(published.charAt(13)));
    }

    /** Remainder 10 maps to check digit 0 here, unlike NIP where it invalidates the number. */
    @Test
    void remainderOfTenBecomesCheckDigitZero() {
        int[] weights9 = {8, 9, 2, 3, 4, 5, 6, 7};
        String body = null;
        for (int candidate = 10000000; candidate < 10001000 && body == null; candidate++) {
            String prefix = String.valueOf(candidate);
            int sum = 0;
            for (int i = 0; i < weights9.length; i++) {
                sum += weights9[i] * Character.getNumericValue(prefix.charAt(i));
            }
            if (sum % 11 == 10) {
                body = prefix;
            }
        }
        assertThat(body).as("a body whose raw remainder is 10").isNotNull();

        assertThat(validator.validate("regon", body + "0"))
                .as("remainder 10 wraps to 0, so this is valid")
                .isEmpty();
        assertThat(validator.validate("regon", body + "1"))
                .as("and nothing else is")
                .isPresent();
    }

    @ParameterizedTest
    @ValueSource(strings = {"1925981", "1925981845", "12345678512", "19259818A"})
    void rejectsAnythingThatIsNotNineOrFourteenBareDigits(String value) {
        assertThat(validator.validate("regon", value))
                .get()
                .extracting(Violation::code)
                .isEqualTo(ViolationCode.PATTERN_INVALID);
    }

    @Test
    void acceptsSeparatorsAndNormalisesThemAway() {
        assertThat(validator.validate("regon", "192 598 184")).isEmpty();
        assertThat(validator.validate("regon", "192-598-184")).isEmpty();
        assertThat(validator.normalise("192-598-184")).isEqualTo("192598184");
    }

    @Test
    void absenceIsNotThisValidatorsProblem() {
        assertThat(validator.validate("regon", null)).isEmpty();
        assertThat(validator.validate("regon", "  ")).isEmpty();
    }
}
